# numpy学习

### 数组切片

numpy切片操作和python的列表操作相差不多，也非常常用。

## 堆叠数组

In [2]:
a = np.arange(9).reshape(3,3)

In [3]:
b  = 2 * a

In [4]:
a,b

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]), array([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]]))

### 水平堆叠函数（hstack,column_stack,concatenate(axis = 1)）

**水平堆叠含义：**(图中A，B为数组)
![](https://tva1.sinaimg.cn/large/006y8mN6gy1g84mcguaq8j30j00c8jrq.jpg)

In [5]:
np.hstack((a,b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [6]:
np.concatenate((a,b), axis = 1)

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

其中比较关键的地方是：concatenate中的**axis**参数为**1**时才表示水平轴方向。

In [7]:
np.column_stack((a, b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

**注意点：**

* 第一个参数都有要合并数组参数的括号,是np.hstack(  (a,b)  )，不是np.hstack(a,b)
* concatenate函数不要忘记axis的含义

### 垂直（竖直）堆叠函数（vstack, row_stack, concatenate(axis=0)）

**垂直堆叠含义：**(图中A，B为数组)
![](https://tva1.sinaimg.cn/large/006y8mN6gy1g84o8tzngfj30hq0d5weu.jpg)

In [8]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [9]:
np.concatenate((a, b), axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [10]:
np.row_stack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

**axis参数**:其中axis=0代表竖直轴（按行），axis=1代表水平（按列），而axis=2代表深度叠加。（可以用一个数组的shape去记忆，比如A数组shape =(a, b, c)）,axis = 0 代表shape的第一个元素，因此操作按照行来进行，而axis=1代表shape的第二个元素，按列，而axis=2代表shape的第三个元素，也就是深度。（**注：**此种记忆方法仅供参考）

注意stack函数与上述堆叠数组方式的不同。

In [11]:
np.stack((a, b), axis = 0 )

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]]])

In [12]:
np.stack((a,b), axis = 1)

array([[[ 0,  1,  2],
        [ 0,  2,  4]],

       [[ 3,  4,  5],
        [ 6,  8, 10]],

       [[ 6,  7,  8],
        [12, 14, 16]]])

In [13]:
np.stack((a, b), axis = 2)

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

## 拆分数组
**注：**可以看作是堆叠的反操作

### 水平拆分（横向拆分）函数（hsplit,split）

**水平拆分含义：**(即按列拆分)
![](https://tva1.sinaimg.cn/large/006y8mN6gy1g84oouwrnkj30h206074e.jpg)

In [16]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
np.hsplit(a, 3) 

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

表示将a数组横向拆解为3部分，即将矩阵$A_{(n,3)}$按照列分块，$A=[a_1,a_2,a_3]$，然后拆成$n$个列向量，分别为$a_1,a_2,a_3$，其中$a_n为$(n*1)$的列向量。

In [19]:
np.split(a, 3, axis = 1) # 因为按照列拆分，所有axis = 1

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

### 竖直拆分（纵向拆分）

**竖直拆分含义：**（即按行拆分）
![](https://tva1.sinaimg.cn/large/006y8mN6gy1g84p0lrx32j30i606a0su.jpg)

In [20]:
np.vsplit(a,3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [21]:
np.split(a, 3, axis = 0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]